section-6/alpha-blog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles
  resources :users, except: [:new]
end

section-6/alpha-blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

section-6/alpha-blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

section-6/alpha-blog/app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z\d]+\.)+[a-z]{2,})\z/i
      record.errors.add attribute, (options[:message] || "is not an email")
    end
  end
end

class User < ApplicationRecord
  has_many :articles

  validates :username,
            presence: true,
            length: { minimum: 3, maximum: 25 },
            uniqueness: { case_sensitive: false }
  validates :email,
            presence: true,
            email: true,
            length: { maximum: 105 },
            uniqueness: { case_sensitive: false }

  before_save { self.email = email.downcase }
  has_secure_password
end

section-6/alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

section-6/alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'articles/new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'articles/edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

section-6/alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

section-6/alpha-blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session.update({ :user_id => user.id })
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "Credentials are not valid"
      render 'sessions/new'
    end
  end

  def destroy
    session.update({ :user_id => nil })
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

section-6/alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up!"
      redirect_to @user
    else
      render 'users/new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'users/edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

section-6/alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    hash = Digest::MD5.hexdigest(user.email)
    size = options[:size]
    url = "https://gravatar.com/avatar/#{hash}?size=#{size}"
    image_tag(url, alt: user.username, class: "rounded mx-auto d-block shadow")
  end
end

section-6/alpha-blog/app/helpers/pages_helper.rb
module PagesHelper
end

section-6/alpha-blog/app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, article.user %>
            <% end  %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Remove", article_path(article), class: "btn btn-outline-danger", data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %>
          </div>
          <div class="card-footer text-muted">
            <%= "Created #{time_ago_in_words(article.created_at)} ago, Updated #{time_ago_in_words(article.updated_at)} ago" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

section-6/alpha-blog/app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with model: @article, class: "shadow p-4 my-4 bg-info rounded", data: { turbo: false }, local: true do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, placeholder: "Title of article", class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, placeholder: "Description of article", class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-4">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info font-weight-bold" %>
    </div>
  </div>
</div>

section-6/alpha-blog/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form' %>

section-6/alpha-blog/app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, :container => false %>
</div>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>

section-6/alpha-blog/app/views/articles/new.html.erb
<h1 class="text-center mt-4">Creating a new article</h1>

<%= render 'form' %>

section-6/alpha-blog/app/views/articles/show.html.erb
<h2 class="text-center mt-4 font-weight-bold"><%= @article.title %></h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow bg-white rounded">
        <div class="card-header font-italic">
          <%= link_to gravatar_for(@article.user), @article.user %>
          <p class="mb-0 mt-2">by <%= @article.user.username if @article.user %></p>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to "Remove", article_path(@article), class: "btn btn-outline-danger", data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %>
        </div>
        <div class="card-footer text-muted">
          <%= "Created #{time_ago_in_words(@article.created_at)} ago, Updated #{time_ago_in_words(@article.updated_at)} ago" %>
        </div>
      </div>
    </div>
  </div>
</div>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>

section-6/alpha-blog/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Alpha Blog</small>
  </div>
</footer>

section-6/alpha-blog/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

section-6/alpha-blog/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Log In", login_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log Out", logout_path, class: "nav-link", data: { "turbo-method" => :delete } %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

section-6/alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="d-flex flex-column">
<%= render 'layouts/navbar' %>
<div id="page-content">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

section-6/alpha-blog/app/views/pages/about.html.erb
<h2>You have reached Alpha blog's about page</h2>

<%= link_to 'Articles listing', articles_path %>
<%= link_to 'Home page', root_path %>

section-6/alpha-blog/app/views/pages/home.html.erb
<div class="container">
  <div class="jumbotron mt-4 text-center text-white">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to
      featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

section-6/alpha-blog/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

section-6/alpha-blog/app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with model: @user, class: "shadow p-4 my-4 bg-info rounded", data: { turbo: false }, local: true do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, placeholder: "Enter a username", class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, placeholder: "Enter your email address", class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :password, placeholder: "Enter a password", class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit (@user.new_record? ? "Sign Up" : "Update account"), class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-4">
      <%= link_to '[ Cancel and return to users listing ]', users_path, class: "text-info font-weight-bold" %>
    </div>
  </div>
</div>

section-6/alpha-blog/app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render 'form' %>

section-6/alpha-blog/app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
          </div>
          <div class="card-footer text-muted">
            <%= "Joined #{time_ago_in_words(user.created_at)} ago" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

section-6/alpha-blog/app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>
<%= render 'form' %>

section-6/alpha-blog/app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center mt-4">
  <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info btn-lg" %>
</div>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, :container => false %>
</div>